export const products = [
  {
    name: 'Massa Adesiva',
    brand: 'Massive Brand',
    description: '80 pastilhas',
    price: 20.0,
    priceBeforeTax: 90.0,
    stock: 100,
    id: 24,
    subCategory: 'Mesas',
    category: 'Escritorio',
    subCategoryId: 1,
    categoryId: 1,
    photo:
      'http://www.cmai.pt/image/cache/data/papelaria/ColaFitacola/UHUpatafix-228x228.JPG',
  },
  {
    name: 'Marcador de Quadro Branco Azul',
    brand: 'Massive Brand',
    description: null,
    price: 30.0,
    priceBeforeTax: 90.0,
    stock: 100,
    id: 25,
    subCategory: 'Mesas',
    category: 'Escritorio',
    subCategoryId: 1,
    categoryId: 1,
    photo:
      'http://www.cmai.pt/image/cache/data/papelaria/Escrita/Monami%20WhiteBoard%20az-228x228.JPG',
  },
  {
    name: 'Marcador Permanente Preto',
    brand: 'Massive Brand',
    description: 'Marcador permamante de escrita fina preto. Cx.10 Unidades',
    price: 100.0,
    priceBeforeTax: 90.0,
    stock: 100,
    id: 26,
    subCategory: 'Mesas',
    category: 'Escritorio',
    subCategoryId: 1,
    categoryId: 1,
    photo:
      'http://www.cmai.pt/image/cache/data/papelaria/Escrita/Edding%201200%20bk-228x228.JPG',
  },
  {
    name: 'Bloco de apontamentos',
    brand: 'Massive Brand',
    description: 'Quadriculado ou Pautado',
    price: 100.0,
    priceBeforeTax: 90.0,
    stock: 100,
    id: 19,
    subCategory: 'Mesas',
    category: 'Escritorio',
    subCategoryId: 1,
    categoryId: 1,
    photo:
      'http://www.cmai.pt/image/cache/data/papelaria/Blocos%20Cadernos/Bloco%20A5%20qudric-228x228.JPG',
  },
  {
    name: 'Bolsas A4',
    brand: 'Massive Brand',
    description: 'Pack 100 Unidades A4 LIsa (Semi Rigidas)',
    price: 100.0,
    priceBeforeTax: 90.0,
    stock: 100,
    id: 20,
    subCategory: 'Mesas',
    category: 'Escritorio',
    subCategoryId: 1,
    categoryId: 1,
    photo:
      'http://www.cmai.pt/image/cache/data/papelaria/Bolsas_Capas/Bolsa%20Catalogo%20connect-228x228.JPG',
  },
  {
    name: 'Contra Capa p/Encadernação',
    brand: 'Massive Brand',
    description:
      'Separador para Encadernação de Cartolina Cromolux 1 Face Preto A4 250gr Cx 100un',
    price: 100.0,
    priceBeforeTax: 90.0,
    stock: 100,
    id: 21,
    subCategory: 'Mesas',
    category: 'Escritorio',
    subCategoryId: 1,
    categoryId: 1,
    photo:
      'http://www.cmai.pt/image/cache/data/papelaria/encadernacao/capas%20encadernar%20chromolux-228x228.JPG',
  },
  {
    name: 'Envelopes 110X220mm s/Janela',
    brand: 'Massive Brand',
    description: 'Cx. 500 Unidades Papel 90gr',
    price: 100.0,
    priceBeforeTax: 90.0,
    stock: 100,
    id: 22,
    subCategory: 'Mesas',
    category: 'Escritorio',
    subCategoryId: 1,
    categoryId: 1,
    photo:
      'http://www.cmai.pt/image/cache/data/papelaria/encadernacao/capas%20encadernar%20chromolux-228x228.JPG',
  },
  {
    name: 'Caderno espiral',
    brand: 'Massive Brand',
    description: 'Caderno Pautado ou Quadriculado A5 120 Folhas 70Gr.',
    price: 40.0,
    priceBeforeTax: 90.0,
    stock: 100,
    id: 23,
    subCategory: 'Mesas',
    category: 'Escritorio',
    subCategoryId: 1,
    categoryId: 1,
    photo:
      'http://www.cmai.pt/image/cache/data/papelaria/Blocos%20Cadernos/Bloco%20espiral%20ambar-228x228.JPG',
  },
  {
    name: 'Navigator Papper A4',
    brand: 'Massive Brand',
    description: 'Papel cópia 80gr Navigator',
    price: 100.0,
    priceBeforeTax: 90.0,
    stock: 100,
    id: 15,
    subCategory: 'Mesas',
    category: 'Escritorio',
    subCategoryId: 1,
    categoryId: 1,
    photo: 'https://www.navigator-paper.com/images/small-universal-new.png',
  },
  {
    name: 'Pasta arquivo A5',
    brand: 'Massive Brand',
    description: 'Pasta Arquivo A5 Ambar L/80mm c/ Alavanca Tela Preta',
    price: 100.0,
    priceBeforeTax: 90.0,
    stock: 100,
    id: 16,
    subCategory: 'Mesas',
    category: 'Escritorio',
    subCategoryId: 1,
    categoryId: 1,
    photo: 'http://www.cmai.pt/image/cache/data/papelaria/Amb4s-228x228.JPG',
  },
];

export const shopCart = [
  {
    name: 'Massa Adesiva',
    brand: 'Massive Brand',
    description: '80 pastilhas',
    price: 20.0,
    priceBeforeTax: 90.0,
    stock: 100,
    quantity: 2,
    id: 24,
    subCategory: 'Mesas',
    category: 'Escritorio',
    subCategoryId: 1,
    categoryId: 1,
    photo:
      'http://www.cmai.pt/image/cache/data/papelaria/ColaFitacola/UHUpatafix-228x228.JPG',
  },
  {
    name: 'Marcador de Quadro Branco Azul',
    brand: 'Massive Brand',
    description: null,
    price: 30.0,
    priceBeforeTax: 90.0,
    stock: 100,
    quantity: 2,
    id: 25,
    subCategory: 'Mesas',
    category: 'Escritorio',
    subCategoryId: 1,
    categoryId: 1,
    photo:
      'http://www.cmai.pt/image/cache/data/papelaria/Escrita/Monami%20WhiteBoard%20az-228x228.JPG',
  },
  {
    name: 'Marcador Permanente Preto',
    brand: 'Massive Brand',
    description: 'Marcador permamante de escrita fina preto. Cx.10 Unidades',
    price: 100.0,
    priceBeforeTax: 90.0,
    stock: 100,
    quantity: 2,
    id: 26,
    subCategory: 'Mesas',
    category: 'Escritorio',
    subCategoryId: 1,
    categoryId: 1,
    photo:
      'http://www.cmai.pt/image/cache/data/papelaria/Escrita/Edding%201200%20bk-228x228.JPG',
  },
  {
    name: 'Bloco de apontamentos',
    brand: 'Massive Brand',
    description: 'Quadriculado ou Pautado',
    price: 100.0,
    priceBeforeTax: 90.0,
    stock: 100,
    quantity: 2,
    id: 19,
    subCategory: 'Mesas',
    category: 'Escritorio',
    subCategoryId: 1,
    categoryId: 1,
    photo:
      'http://www.cmai.pt/image/cache/data/papelaria/Blocos%20Cadernos/Bloco%20A5%20qudric-228x228.JPG',
  },
  {
    name: 'Bolsas A4',
    brand: 'Massive Brand',
    description: 'Pack 100 Unidades A4 LIsa (Semi Rigidas)',
    price: 100.0,
    priceBeforeTax: 90.0,
    stock: 100,
    quantity: 2,
    id: 20,
    subCategory: 'Mesas',
    category: 'Escritorio',
    subCategoryId: 1,
    categoryId: 1,
    photo:
      'http://www.cmai.pt/image/cache/data/papelaria/Bolsas_Capas/Bolsa%20Catalogo%20connect-228x228.JPG',
  },
  {
    name: 'Contra Capa p/Encadernação',
    brand: 'Massive Brand',
    description:
      'Separador para Encadernação de Cartolina Cromolux 1 Face Preto A4 250gr Cx 100un',
    price: 100.0,
    priceBeforeTax: 90.0,
    stock: 100,
    quantity: 2,
    id: 21,
    subCategory: 'Mesas',
    category: 'Escritorio',
    subCategoryId: 1,
    categoryId: 1,
    photo:
      'http://www.cmai.pt/image/cache/data/papelaria/encadernacao/capas%20encadernar%20chromolux-228x228.JPG',
  },
  {
    name: 'Envelopes 110X220mm s/Janela',
    brand: 'Massive Brand',
    description: 'Cx. 500 Unidades Papel 90gr',
    price: 100.0,
    priceBeforeTax: 90.0,
    stock: 100,
    quantity: 2,
    id: 22,
    subCategory: 'Mesas',
    category: 'Escritorio',
    subCategoryId: 1,
    categoryId: 1,
    photo:
      'http://www.cmai.pt/image/cache/data/papelaria/encadernacao/capas%20encadernar%20chromolux-228x228.JPG',
  },
  {
    name: 'Caderno espiral',
    brand: 'Massive Brand',
    description: 'Caderno Pautado ou Quadriculado A5 120 Folhas 70Gr.',
    price: 40.0,
    priceBeforeTax: 90.0,
    stock: 100,
    quantity: 2,
    id: 23,
    subCategory: 'Mesas',
    category: 'Escritorio',
    subCategoryId: 1,
    categoryId: 1,
    photo:
      'http://www.cmai.pt/image/cache/data/papelaria/Blocos%20Cadernos/Bloco%20espiral%20ambar-228x228.JPG',
  },
  {
    name: 'Navigator Papper A4',
    brand: 'Massive Brand',
    description: 'Papel cópia 80gr Navigator',
    price: 100.0,
    priceBeforeTax: 90.0,
    stock: 100,
    quantity: 2,
    id: 15,
    subCategory: 'Mesas',
    category: 'Escritorio',
    subCategoryId: 1,
    categoryId: 1,
    photo: 'https://www.navigator-paper.com/images/small-universal-new.png',
  },
  {
    name: 'Pasta arquivo A5',
    brand: 'Massive Brand',
    description: 'Pasta Arquivo A5 Ambar L/80mm c/ Alavanca Tela Preta',
    price: 100.0,
    priceBeforeTax: 90.0,
    stock: 100,
    quantity: 2,
    id: 16,
    subCategory: 'Mesas',
    category: 'Escritorio',
    subCategoryId: 1,
    categoryId: 1,
    photo: 'http://www.cmai.pt/image/cache/data/papelaria/Amb4s-228x228.JPG',
  },
];
